name: buidling and pushing exporter image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
  DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}

jobs:
  audit:
    name: Run Code Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Run Code Audit
        run: make audit

  build-and-push:
    name: Build and Push Docker Image
    needs: audit  # Ensures audit passes before building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Build the Golang Application
        run: make build/exporter/dockerImage DOCKER_IMAGENAME="${{ vars.DOCKER_IMAGE_NAME}}"

      - name: Log in to docker registry
        run: docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASS

      - name: Tag and Push Docker Image
        run: |
          IMAGE_TAG=`docker image ls | grep -i polkaexporter | awk 'BEGIN{FS=" "}{print$2}'`
          docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG

